language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  
services:
  - mysql

env:
  - WP_VERSION=latest WP_MULTISITE=0

install:
  - composer install --prefer-dist

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: vendor/phpunit/phpunit/phpunit -c phpunit.xml
